name: Update and Upload Dependencies

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  update-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd app
          npm install

      - name: Commit and Push Changes
        run: |
          cd app
          npm install webpack webpack-cli --save-dev
          npx webpack
          rm -r node_modules
          
      - uses: actions/upload-artifact@v3
        with:
          name: openstreammusic-web
          path: ./app

